"""add unique constraints for idempotent M0 pool upserts

Revision ID: 16eb5a1db6ef
Revises: d9e96bce67a8
Create Date: 2026-08-03 17:07:30.972140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16eb5a1db6ef'
down_revision: Union[str, None] = 'd9e96bce67a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_flight_definitions_carrier_flight_route', 'flight_definitions', ['carrier_code', 'flight_number', 'origin_airport', 'dest_airport'])
    op.drop_index('ix_flight_volatility_stats_flight_definition_id', table_name='flight_volatility_stats')
    op.create_unique_constraint('uq_flight_volatility_stats_flight_definition_id', 'flight_volatility_stats', ['flight_definition_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flight_volatility_stats_flight_definition_id', 'flight_volatility_stats', type_='unique')
    op.create_index('ix_flight_volatility_stats_flight_definition_id', 'flight_volatility_stats', ['flight_definition_id'], unique=False)
    op.drop_constraint('uq_flight_definitions_carrier_flight_route', 'flight_definitions', type_='unique')
    # ### end Alembic commands ###
