"""add job_cursors and aerodatabox_call_log tables

Revision ID: 1830b2faef8f
Revises: 16eb5a1db6ef
Create Date: 2026-08-03 17:40:41.866492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1830b2faef8f'
down_revision: Union[str, None] = '16eb5a1db6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cursors',
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('cursor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('aerodatabox_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_definition_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flight_definition_id'], ['flight_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aerodatabox_call_log_flight_definition_id'), 'aerodatabox_call_log', ['flight_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aerodatabox_call_log_flight_definition_id'), table_name='aerodatabox_call_log')
    op.drop_table('aerodatabox_call_log')
    op.drop_table('job_cursors')
    # ### end Alembic commands ###
