"""initial schema

Revision ID: 3e84e9a39b7c
Revises: 
Create Date: 2026-08-03 15:11:00.671198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e84e9a39b7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # required for gen_random_uuid() used as the default on every PK below
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_definitions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('carrier_code', sa.String(length=2), nullable=False),
    sa.Column('flight_number', sa.String(length=6), nullable=False),
    sa.Column('origin_airport', sa.String(length=3), nullable=False),
    sa.Column('dest_airport', sa.String(length=3), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('typical_dep_time', sa.Time(), nullable=False),
    sa.Column('typical_arr_time', sa.Time(), nullable=False),
    sa.Column('distance_bucket', sa.Enum('short', 'medium', 'long', name='distance_bucket'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flight_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('flight_definition_id', sa.UUID(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('scheduled_dep_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_arr_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_dep_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arr_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'boarding', 'departed', 'airborne', 'landed', 'delayed', 'diverted', 'cancelled', name='flight_instance_status'), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('current_icao24', sa.String(length=6), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_definition_id'], ['flight_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_instances_flight_definition_id', 'flight_instances', ['flight_definition_id'])
    op.create_index('ix_flight_instances_flight_date', 'flight_instances', ['flight_date'])
    op.create_table('flight_volatility_stats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('flight_definition_id', sa.UUID(), nullable=False),
    sa.Column('on_time_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_delay_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('delay_stddev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cancellation_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diversion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_definition_id'], ['flight_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_volatility_stats_flight_definition_id', 'flight_volatility_stats', ['flight_definition_id'])
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallets_user_id', 'wallets', ['user_id'])
    op.create_table('state_vector_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('flight_instance_id', sa.UUID(), nullable=False),
    sa.Column('polled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('velocity_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vertical_rate', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('on_ground', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flight_instance_id'], ['flight_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_state_vector_log_flight_instance_id', 'state_vector_log', ['flight_instance_id'])
    op.create_table('wallet_picks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('flight_instance_id', sa.UUID(), nullable=False),
    sa.Column('staked_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.Enum('active', 'resolved_win', 'resolved_loss', 'cashed_out', name='wallet_pick_status'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('resolved_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cashed_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_instance_id'], ['flight_instances.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_picks_wallet_id', 'wallet_picks', ['wallet_id'])
    op.create_index('ix_wallet_picks_flight_instance_id', 'wallet_picks', ['flight_instance_id'])
    op.create_table('wallet_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_pick_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('decay_tick', 'gain_tick', 'delay_penalty', 'cancellation_penalty', 'diversion_penalty', 'cash_out', 'resolution', name='wallet_event_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['wallet_pick_id'], ['wallet_picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_events_wallet_pick_id', 'wallet_events', ['wallet_pick_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_events')
    op.drop_table('wallet_picks')
    op.drop_table('state_vector_log')
    op.drop_table('wallets')
    op.drop_table('flight_volatility_stats')
    op.drop_table('flight_instances')
    op.drop_table('users')
    op.drop_table('flight_definitions')
    # ### end Alembic commands ###

    # postgres ENUM types are not dropped automatically when their table is
    # dropped, since a type could in principle be shared across tables
    for enum_name in (
        'wallet_event_type',
        'wallet_pick_status',
        'flight_instance_status',
        'distance_bucket',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')

    op.execute('DROP EXTENSION IF EXISTS pgcrypto')
