"""add opensky_raw_poll_log table

Revision ID: 46d7f946917e
Revises: 4a17359909e7
Create Date: 2026-08-03 18:05:39.091548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46d7f946917e'
down_revision: Union[str, None] = '4a17359909e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opensky_raw_poll_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('polled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lamin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('lomin', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('lamax', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('lomax', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('state_vector_count', sa.Integer(), nullable=True),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opensky_raw_poll_log')
    # ### end Alembic commands ###
