"""add flight_date to aerodatabox_call_log

Revision ID: 4a17359909e7
Revises: 1830b2faef8f
Create Date: 2026-08-03 17:47:20.212852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a17359909e7'
down_revision: Union[str, None] = '1830b2faef8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aerodatabox_call_log', sa.Column('flight_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aerodatabox_call_log', 'flight_date')
    # ### end Alembic commands ###
