"""add wallet_picks.last_charged_delay_minutes for incremental delay charging

Revision ID: 5d424896ef0b
Revises: 46d7f946917e
Create Date: 2026-08-03 21:25:57.782643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d424896ef0b'
down_revision: Union[str, None] = '46d7f946917e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_picks', sa.Column('last_charged_delay_minutes', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_picks', 'last_charged_delay_minutes')
    # ### end Alembic commands ###
