"""add bts ontime performance raw staging table

Revision ID: d9e96bce67a8
Revises: 3e84e9a39b7c
Create Date: 2026-08-03 15:25:07.289285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e96bce67a8'
down_revision: Union[str, None] = '3e84e9a39b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bts_ontime_performance_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('carrier_code', sa.String(length=2), nullable=False),
    sa.Column('flight_number', sa.String(length=6), nullable=False),
    sa.Column('origin_airport', sa.String(length=3), nullable=False),
    sa.Column('dest_airport', sa.String(length=3), nullable=False),
    sa.Column('crs_dep_time_local', sa.Time(), nullable=True),
    sa.Column('crs_arr_time_local', sa.Time(), nullable=True),
    sa.Column('arr_delay_minutes', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('arr_del15', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('diverted', sa.Boolean(), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bts_raw_carrier_flight_route', 'bts_ontime_performance_raw', ['carrier_code', 'flight_number', 'origin_airport', 'dest_airport'], unique=False)
    op.create_index('ix_bts_raw_year_month', 'bts_ontime_performance_raw', ['year', 'month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bts_raw_year_month', table_name='bts_ontime_performance_raw')
    op.drop_index('ix_bts_raw_carrier_flight_route', table_name='bts_ontime_performance_raw')
    op.drop_table('bts_ontime_performance_raw')
    # ### end Alembic commands ###
