"""add wheels-off/wheels-on columns to bts staging table

Revision ID: e23e80bc52b9
Revises: 5d424896ef0b
Create Date: 2026-08-04 12:27:26.775989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23e80bc52b9'
down_revision: Union[str, None] = '5d424896ef0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bts_ontime_performance_raw', sa.Column('wheels_off_local', sa.Time(), nullable=True))
    op.add_column('bts_ontime_performance_raw', sa.Column('wheels_on_local', sa.Time(), nullable=True))
    op.add_column('bts_ontime_performance_raw', sa.Column('wheels_off_delay_minutes', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('bts_ontime_performance_raw', sa.Column('wheels_on_delay_minutes', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('bts_ontime_performance_raw', sa.Column('wheels_on_del15', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bts_ontime_performance_raw', 'wheels_on_del15')
    op.drop_column('bts_ontime_performance_raw', 'wheels_on_delay_minutes')
    op.drop_column('bts_ontime_performance_raw', 'wheels_off_delay_minutes')
    op.drop_column('bts_ontime_performance_raw', 'wheels_on_local')
    op.drop_column('bts_ontime_performance_raw', 'wheels_off_local')
    # ### end Alembic commands ###
